schema_version: 1

context:
  name: basedpyright
  version: "1.30.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/basedpyright-${{ version }}.tar.gz
  sha256: 45f5c94b92a8cb9506998c6d29129becd5a2118f14fdbc0df289b96d6a8ff8bc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - basedpyright = basedpyright.pyright:main
      - basedpyright-langserver = basedpyright.langserver:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend >=2.3.0
    - nodejs-wheel >=20.13.1
    - typing_extensions >=4.12.2
    - docify >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - nodejs-wheel >=20.13.1

tests:
  - python:
      imports:
        - basedpyright
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - basedpyright --help

about:
  summary: static type checking for Python (but based)
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - basedpyright/dist/typeshed-fallback/LICENSE
    - docstubs/LICENSE
    - packages/pyright/LICENSE.txt
    - packages/pyright/dist/typeshed-fallback/LICENSE
    - packages/pyright-internal/node_modules/@types/lodash/LICENSE
    - packages/pyright-internal/typeshed-fallback/LICENSE
  homepage: https://github.com/DetachHead/basedpyright

extra:
  recipe-maintainers:
    - lucascolley
    - DetachHead
